//ecommerce/backend/SeedData.js
// Mongoose seed script for your e-commerce database (mobiles, smartphones, video games, consoles, watches & headphones)
// Run this script after connecting to MongoDB and importing your models.

import mongoose from "mongoose";
import User from "./models/User.js"; // Adjust path if needed
import Category from "./models/Category.js"; // Adjust path if needed
import Product from "./models/Product.js"; // Adjust path if needed
import Order from "./models/Order.js"; // Adjust path if needed
import dotenv from "dotenv";

dotenv.config();

// Connect to MongoDB
await mongoose.connect(process.env.MONGO_URI);

// Optional: Clear existing data before seeding
await Promise.all([
  User.deleteMany({}),
  Category.deleteMany({}),
  Product.deleteMany({}),
  Order.deleteMany({}),
]);

// 1. Seed Categories (6 categories)
const categories = [
  {
    name: "Smartphones",
    description:
      "Latest smartphones from top brands with cutting-edge features.",
    image: "https://example.com/images/categories/smartphones.jpg",
  },
  {
    name: "Mobile Accessories",
    description: "Cases, chargers, earphones, screen protectors, and more.",
    image: "https://example.com/images/categories/accessories.jpg",
  },
  {
    name: "Consoles",
    description: "PlayStation, Xbox, Nintendo consoles and bundles.",
    image: "https://example.com/images/categories/consoles.jpg",
  },
  {
    name: "Video Games",
    description: "Popular video games for all major platforms.",
    image: "https://example.com/images/categories/games.jpg",
  },
  {
    name: "Watches",
    description:
      "Premium smartwatches with health tracking, notifications, and stylish designs.",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/028/895/422/small_2x/smart-watch-banner-social-media-post-design-ads-banner-template-free-vector.jpg",
  },
  {
    name: "Headphones",
    description:
      "High-quality over-ear wireless headphones with noise cancellation and superior sound.",
    image:
      "https://img.pikbest.com/templates/20250813/wireless-headphone-website-hero-banner-and-landing-page-ui-design_11827161.jpg!bw700",
  },
];

const createdCategories = await Category.insertMany(categories);

// Map category IDs for easy reference
const catIds = {
  smartphones: createdCategories[0]._id,
  accessories: createdCategories[1]._id,
  consoles: createdCategories[2]._id,
  games: createdCategories[3]._id,
  watches: createdCategories[4]._id,
  headphones: createdCategories[5]._id,
};

// 2. Seed Products (5 per category = 30 products)
const products = [
  /* ───────────── Smartphones (10) ───────────── */
  {
    name: "iPhone 16 Pro",
    brand: "Apple",
    description: "Premium iPhone with A18 Pro chip.",
    price: 1099,
    salePrice: 999,
    discountPercentage: 9,
    stock: 50,
    featured: true,
    onSale: true,
    images: ["https://example.com/iphone16pro.jpg"],
    rating: 4.9,
    reviews: 500,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-09-20"),
    specifications: [{ label: "Chip", value: "A18 Pro" }],
    stockStatus: "in-stock",
  },
  {
    name: "Samsung Galaxy S25",
    brand: "Samsung",
    description: "Flagship Android phone.",
    price: 999,
    salePrice: null,
    discountPercentage: null,
    stock: 60,
    featured: true,
    onSale: false,
    images: ["https://example.com/galaxy-s25.jpg"],
    rating: 4.8,
    reviews: 410,
    category: catIds.smartphones,
    countryOfOrigin: "Vietnam",
    releaseDate: new Date("2025-01-20"),
    specifications: [{ label: "Display", value: "AMOLED 120Hz" }],
    stockStatus: "in-stock",
  },
  {
    name: "Google Pixel 9",
    brand: "Google",
    description: "Clean Android with AI camera.",
    price: 799,
    salePrice: 749,
    discountPercentage: 6,
    stock: 70,
    featured: false,
    onSale: true,
    images: ["https://example.com/pixel9.jpg"],
    rating: 4.7,
    reviews: 300,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-08-25"),
    specifications: [{ label: "Camera", value: "50MP AI" }],
    stockStatus: "in-stock",
  },
  {
    name: "OnePlus 13R",
    brand: "OnePlus",
    description: "Fast and smooth performance.",
    price: 699,
    salePrice: 649,
    discountPercentage: 7,
    stock: 65,
    featured: false,
    onSale: true,
    images: ["https://example.com/oneplus13r.jpg"],
    rating: 4.6,
    reviews: 210,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2025-01-05"),
    specifications: [{ label: "Charging", value: "100W" }],
    stockStatus: "in-stock",
  },
  {
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    description: "Photography-focused flagship.",
    price: 899,
    salePrice: null,
    discountPercentage: null,
    stock: 55,
    featured: true,
    onSale: false,
    images: ["https://example.com/xiaomi14ultra.jpg"],
    rating: 4.7,
    reviews: 260,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-02-22"),
    specifications: [{ label: "Camera", value: "Leica Quad" }],
    stockStatus: "in-stock",
  },
  {
    name: "Sony Xperia 1 VI",
    brand: "Sony",
    description: "Cinema-grade smartphone.",
    price: 999,
    salePrice: 949,
    discountPercentage: 5,
    stock: 40,
    featured: false,
    onSale: true,
    images: ["https://example.com/xperia1vi.jpg"],
    rating: 4.5,
    reviews: 180,
    category: catIds.smartphones,
    countryOfOrigin: "Japan",
    releaseDate: new Date("2024-06-01"),
    specifications: [{ label: "Display", value: "4K OLED" }],
    stockStatus: "in-stock",
  },
  {
    name: "Oppo Find X7 Pro",
    brand: "Oppo",
    description: "Elegant design with strong camera.",
    price: 849,
    salePrice: null,
    discountPercentage: null,
    stock: 48,
    featured: false,
    onSale: false,
    images: ["https://example.com/findx7pro.jpg"],
    rating: 4.6,
    reviews: 200,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-01-10"),
    specifications: [{ label: "Camera", value: "Hasselblad" }],
    stockStatus: "in-stock",
  },
  {
    name: "Vivo X100 Pro",
    brand: "Vivo",
    description: "Premium camera phone.",
    price: 799,
    salePrice: 749,
    discountPercentage: 6,
    stock: 52,
    featured: false,
    onSale: true,
    images: ["https://example.com/vivox100pro.jpg"],
    rating: 4.6,
    reviews: 195,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-03-15"),
    specifications: [{ label: "Lens", value: "ZEISS" }],
    stockStatus: "in-stock",
  },
  {
    name: "Asus ROG Phone 8",
    brand: "Asus",
    description: "Ultimate gaming smartphone.",
    price: 999,
    salePrice: null,
    discountPercentage: null,
    stock: 35,
    featured: true,
    onSale: false,
    images: ["https://example.com/rogphone8.jpg"],
    rating: 4.8,
    reviews: 230,
    category: catIds.smartphones,
    countryOfOrigin: "Taiwan",
    releaseDate: new Date("2024-04-12"),
    specifications: [{ label: "Cooling", value: "GameCool 8" }],
    stockStatus: "in-stock",
  },
  {
    name: "Nokia X50",
    brand: "Nokia",
    description: "Reliable phone with clean Android.",
    price: 499,
    salePrice: 459,
    discountPercentage: 8,
    stock: 80,
    featured: false,
    onSale: true,
    images: ["https://example.com/nokiax50.jpg"],
    rating: 4.4,
    reviews: 140,
    category: catIds.smartphones,
    countryOfOrigin: "Finland",
    releaseDate: new Date("2023-11-10"),
    specifications: [{ label: "OS", value: "Android One" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Accessories (10) ───────────── */
  {
    name: "Anker Nano Charger",
    brand: "Anker",
    description: "30W fast USB-C charger.",
    price: 39,
    salePrice: 29,
    discountPercentage: 25,
    stock: 200,
    featured: true,
    onSale: true,
    images: ["https://example.com/anker-nano.jpg"],
    rating: 4.8,
    reviews: 600,
    category: catIds.accessories,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-05-01"),
    specifications: [{ label: "Output", value: "30W" }],
    stockStatus: "in-stock",
  },
  {
    name: "Samsung Wireless Power Bank",
    brand: "Samsung",
    description: "Wireless charging power bank.",
    price: 79,
    salePrice: null,
    discountPercentage: null,
    stock: 150,
    featured: false,
    onSale: false,
    images: ["https://example.com/samsung-powerbank.jpg"],
    rating: 4.6,
    reviews: 310,
    category: catIds.accessories,
    countryOfOrigin: "Vietnam",
    releaseDate: new Date("2022-09-15"),
    specifications: [{ label: "Capacity", value: "10000mAh" }],
    stockStatus: "in-stock",
  },
  {
    name: "Apple MagSafe Wallet",
    brand: "Apple",
    description: "Leather MagSafe wallet.",
    price: 59,
    salePrice: 49,
    discountPercentage: 17,
    stock: 90,
    featured: false,
    onSale: true,
    images: ["https://example.com/magsafe-wallet.jpg"],
    rating: 4.5,
    reviews: 280,
    category: catIds.accessories,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-10-10"),
    specifications: [{ label: "Material", value: "Leather" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Consoles (5) ───────────── */
  {
    name: "PlayStation 5",
    brand: "Sony",
    description: "Next-gen gaming console.",
    price: 499,
    salePrice: null,
    discountPercentage: null,
    stock: 40,
    featured: true,
    onSale: false,
    images: ["https://example.com/ps5.jpg"],
    rating: 4.9,
    reviews: 2000,
    category: catIds.consoles,
    countryOfOrigin: "China",
    releaseDate: new Date("2020-11-12"),
    specifications: [{ label: "Storage", value: "825GB SSD" }],
    stockStatus: "in-stock",
  },
  {
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    description: "Portable gaming console.",
    price: 349,
    salePrice: 319,
    discountPercentage: 9,
    stock: 70,
    featured: true,
    onSale: true,
    images: ["https://example.com/switch-oled.jpg"],
    rating: 4.8,
    reviews: 1500,
    category: catIds.consoles,
    countryOfOrigin: "Japan",
    releaseDate: new Date("2021-10-08"),
    specifications: [{ label: "Display", value: "OLED" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Games (10) ───────────── */
  {
    name: "GTA VI",
    brand: "Rockstar Games",
    description: "Open-world action game.",
    price: 69,
    salePrice: null,
    discountPercentage: null,
    stock: 300,
    featured: true,
    onSale: false,
    images: ["https://example.com/gta6.jpg"],
    rating: 4.9,
    reviews: 5000,
    category: catIds.games,
    countryOfOrigin: "USA",
    releaseDate: new Date("2025-02-01"),
    specifications: [{ label: "Genre", value: "Action" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Watches (7) ───────────── */
  {
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    description: "Rugged smartwatch.",
    price: 799,
    salePrice: null,
    discountPercentage: null,
    stock: 60,
    featured: true,
    onSale: false,
    images: ["https://example.com/apple-ultra2.jpg"],
    rating: 4.8,
    reviews: 700,
    category: catIds.watches,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-09-20"),
    specifications: [{ label: "Case", value: "Titanium" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Headphones (5) ───────────── */
  {
    name: "Sony WH-1000XM6",
    brand: "Sony",
    description: "Top-tier noise cancellation.",
    price: 429,
    salePrice: 399,
    discountPercentage: 7,
    stock: 90,
    featured: true,
    onSale: true,
    images: ["https://example.com/xm6.jpg"],
    rating: 4.9,
    reviews: 1200,
    category: catIds.headphones,
    countryOfOrigin: "Malaysia",
    releaseDate: new Date("2024-07-01"),
    specifications: [{ label: "ANC", value: "Adaptive" }],
    stockStatus: "in-stock",
  },
  {
    name: "Realme GT 6 Pro",
    brand: "Realme",
    description: "High-performance phone with AMOLED display.",
    price: 599,
    salePrice: 549,
    discountPercentage: 8,
    stock: 90,
    featured: false,
    onSale: true,
    images: ["https://example.com/realme-gt6pro.jpg"],
    rating: 4.5,
    reviews: 160,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-05-12"),
    specifications: [{ label: "Processor", value: "Snapdragon 8s Gen 3" }],
    stockStatus: "in-stock",
  },
  {
    name: "Infinix Zero 30",
    brand: "Infinix",
    description: "Affordable phone with strong camera.",
    price: 329,
    salePrice: null,
    discountPercentage: null,
    stock: 140,
    featured: false,
    onSale: false,
    images: ["https://example.com/infinix-zero30.jpg"],
    rating: 4.3,
    reviews: 210,
    category: catIds.smartphones,
    countryOfOrigin: "Hong Kong",
    releaseDate: new Date("2023-09-01"),
    specifications: [{ label: "Camera", value: "50MP Front" }],
    stockStatus: "in-stock",
  },
  {
    name: "Tecno Phantom V Fold",
    brand: "Tecno",
    description: "Foldable smartphone with large display.",
    price: 999,
    salePrice: 899,
    discountPercentage: 10,
    stock: 25,
    featured: true,
    onSale: true,
    images: ["https://example.com/phantom-v-fold.jpg"],
    rating: 4.4,
    reviews: 95,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-02-20"),
    specifications: [{ label: "Type", value: "Foldable AMOLED" }],
    stockStatus: "in-stock",
  },
  {
    name: "Honor Magic 6 Pro",
    brand: "Honor",
    description: "Premium design with powerful camera.",
    price: 899,
    salePrice: null,
    discountPercentage: null,
    stock: 45,
    featured: true,
    onSale: false,
    images: ["https://example.com/honor-magic6.jpg"],
    rating: 4.6,
    reviews: 175,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-01-15"),
    specifications: [{ label: "Display", value: "LTPO OLED" }],
    stockStatus: "in-stock",
  },
  {
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    description: "Clean Android with fast charging.",
    price: 649,
    salePrice: 599,
    discountPercentage: 8,
    stock: 70,
    featured: false,
    onSale: true,
    images: ["https://example.com/edge50pro.jpg"],
    rating: 4.5,
    reviews: 140,
    category: catIds.smartphones,
    countryOfOrigin: "USA",
    releaseDate: new Date("2024-04-10"),
    specifications: [{ label: "Charging", value: "125W" }],
    stockStatus: "in-stock",
  },
  {
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    description: "Minimal design with glyph interface.",
    price: 399,
    salePrice: 369,
    discountPercentage: 7,
    stock: 110,
    featured: false,
    onSale: true,
    images: ["https://example.com/nothing-2a.jpg"],
    rating: 4.4,
    reviews: 190,
    category: catIds.smartphones,
    countryOfOrigin: "UK",
    releaseDate: new Date("2024-03-05"),
    specifications: [{ label: "Design", value: "Glyph LED" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Accessories (6) ───────────── */
  {
    name: "Baseus 65W GaN Charger",
    brand: "Baseus",
    description: "Compact GaN fast charger.",
    price: 49,
    salePrice: 39,
    discountPercentage: 20,
    stock: 220,
    featured: true,
    onSale: true,
    images: ["https://example.com/baseus-gan.jpg"],
    rating: 4.7,
    reviews: 430,
    category: catIds.accessories,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-08-10"),
    specifications: [{ label: "Output", value: "65W" }],
    stockStatus: "in-stock",
  },
  {
    name: "Ugreen USB-C Hub",
    brand: "Ugreen",
    description: "Multiport adapter for laptops.",
    price: 59,
    salePrice: null,
    discountPercentage: null,
    stock: 160,
    featured: false,
    onSale: false,
    images: ["https://example.com/ugreen-hub.jpg"],
    rating: 4.6,
    reviews: 300,
    category: catIds.accessories,
    countryOfOrigin: "China",
    releaseDate: new Date("2022-06-20"),
    specifications: [{ label: "Ports", value: "HDMI, USB, PD" }],
    stockStatus: "in-stock",
  },
  {
    name: "Sandisk Extreme 1TB SSD",
    brand: "SanDisk",
    description: "Portable high-speed SSD.",
    price: 149,
    salePrice: 129,
    discountPercentage: 13,
    stock: 85,
    featured: false,
    onSale: true,
    images: ["https://example.com/sandisk-ssd.jpg"],
    rating: 4.8,
    reviews: 520,
    category: catIds.accessories,
    countryOfOrigin: "USA",
    releaseDate: new Date("2023-02-14"),
    specifications: [{ label: "Speed", value: "1050MB/s" }],
    stockStatus: "in-stock",
  },
  {
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    description: "Premium productivity mouse.",
    price: 99,
    salePrice: null,
    discountPercentage: null,
    stock: 95,
    featured: true,
    onSale: false,
    images: ["https://example.com/mx-master-3s.jpg"],
    rating: 4.9,
    reviews: 870,
    category: catIds.accessories,
    countryOfOrigin: "Switzerland",
    releaseDate: new Date("2022-09-01"),
    specifications: [{ label: "Sensor", value: "8000 DPI" }],
    stockStatus: "in-stock",
  },
  {
    name: "Razer Huntsman Mini",
    brand: "Razer",
    description: "Compact mechanical keyboard.",
    price: 119,
    salePrice: 99,
    discountPercentage: 17,
    stock: 75,
    featured: false,
    onSale: true,
    images: ["https://example.com/huntsman-mini.jpg"],
    rating: 4.6,
    reviews: 360,
    category: catIds.accessories,
    countryOfOrigin: "USA",
    releaseDate: new Date("2021-11-10"),
    specifications: [{ label: "Switches", value: "Optical" }],
    stockStatus: "in-stock",
  },
  {
    name: "JBL Flip 6",
    brand: "JBL",
    description: "Portable Bluetooth speaker.",
    price: 129,
    salePrice: 109,
    discountPercentage: 15,
    stock: 130,
    featured: false,
    onSale: true,
    images: ["https://example.com/jbl-flip6.jpg"],
    rating: 4.7,
    reviews: 540,
    category: catIds.accessories,
    countryOfOrigin: "USA",
    releaseDate: new Date("2022-01-05"),
    specifications: [{ label: "Waterproof", value: "IP67" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Consoles (4) ───────────── */
  {
    name: "Xbox Series S",
    brand: "Microsoft",
    description: "Compact next-gen console.",
    price: 299,
    salePrice: 279,
    discountPercentage: 7,
    stock: 85,
    featured: false,
    onSale: true,
    images: ["https://example.com/xbox-series-s.jpg"],
    rating: 4.6,
    reviews: 980,
    category: catIds.consoles,
    countryOfOrigin: "China",
    releaseDate: new Date("2020-11-10"),
    specifications: [{ label: "Resolution", value: "1440p" }],
    stockStatus: "in-stock",
  },
  {
    name: "Steam Deck OLED",
    brand: "Valve",
    description: "Portable PC gaming console.",
    price: 549,
    salePrice: null,
    discountPercentage: null,
    stock: 35,
    featured: true,
    onSale: false,
    images: ["https://example.com/steamdeck-oled.jpg"],
    rating: 4.8,
    reviews: 420,
    category: catIds.consoles,
    countryOfOrigin: "USA",
    releaseDate: new Date("2023-11-16"),
    specifications: [{ label: "Display", value: "OLED" }],
    stockStatus: "in-stock",
  },
  {
    name: "PlayStation VR2",
    brand: "Sony",
    description: "Next-gen VR headset.",
    price: 549,
    salePrice: 499,
    discountPercentage: 9,
    stock: 30,
    featured: true,
    onSale: true,
    images: ["https://example.com/psvr2.jpg"],
    rating: 4.7,
    reviews: 310,
    category: catIds.consoles,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-02-22"),
    specifications: [{ label: "Resolution", value: "4K HDR" }],
    stockStatus: "in-stock",
  },
  {
    name: "Nintendo Switch Lite",
    brand: "Nintendo",
    description: "Handheld-only console.",
    price: 199,
    salePrice: 179,
    discountPercentage: 10,
    stock: 120,
    featured: false,
    onSale: true,
    images: ["https://example.com/switch-lite.jpg"],
    rating: 4.5,
    reviews: 860,
    category: catIds.consoles,
    countryOfOrigin: "Japan",
    releaseDate: new Date("2019-09-20"),
    specifications: [{ label: "Mode", value: "Handheld" }],
    stockStatus: "in-stock",
  },

  /* ───────────── Games (4) ───────────── */
  {
    name: "Elden Ring",
    brand: "FromSoftware",
    description: "Challenging open-world RPG.",
    price: 59,
    salePrice: 39,
    discountPercentage: 34,
    stock: 200,
    featured: true,
    onSale: true,
    images: ["https://example.com/elden-ring.jpg"],
    rating: 4.9,
    reviews: 3200,
    category: catIds.games,
    countryOfOrigin: "Japan",
    releaseDate: new Date("2022-02-25"),
    specifications: [{ label: "Genre", value: "RPG" }],
    stockStatus: "in-stock",
  },
  {
    name: "Call of Duty: Modern Warfare III",
    brand: "Activision",
    description: "Fast-paced FPS action.",
    price: 69,
    salePrice: 59,
    discountPercentage: 14,
    stock: 260,
    featured: true,
    onSale: true,
    images: ["https://example.com/mw3.jpg"],
    rating: 4.4,
    reviews: 1800,
    category: catIds.games,
    countryOfOrigin: "USA",
    releaseDate: new Date("2023-11-10"),
    specifications: [{ label: "Mode", value: "Multiplayer" }],
    stockStatus: "in-stock",
  },
  {
    name: "Forza Horizon 5",
    brand: "Playground Games",
    description: "Open-world racing game.",
    price: 59,
    salePrice: 39,
    discountPercentage: 34,
    stock: 180,
    featured: false,
    onSale: true,
    images: ["https://example.com/forza5.jpg"],
    rating: 4.8,
    reviews: 2100,
    category: catIds.games,
    countryOfOrigin: "UK",
    releaseDate: new Date("2021-11-09"),
    specifications: [{ label: "Genre", value: "Racing" }],
    stockStatus: "in-stock",
  },
  {
    name: "God of War Ragnarök",
    brand: "Sony Santa Monica",
    description: "Epic Norse mythology adventure.",
    price: 69,
    salePrice: null,
    discountPercentage: null,
    stock: 150,
    featured: true,
    onSale: false,
    images: ["https://example.com/gow-ragnarok.jpg"],
    rating: 4.9,
    reviews: 2900,
    category: catIds.games,
    countryOfOrigin: "USA",
    releaseDate: new Date("2022-11-09"),
    specifications: [{ label: "Story", value: "Single-player" }],
    stockStatus: "in-stock",
  },
  {
    name: "Samsung Galaxy A55",
    brand: "Samsung",
    description: "Mid-range AMOLED phone.",
    price: 449,
    salePrice: 399,
    discountPercentage: 11,
    stock: 120,
    featured: false,
    onSale: true,
    images: ["https://example.com/a55.jpg"],
    rating: 4.4,
    reviews: 320,
    category: catIds.smartphones,
    countryOfOrigin: "Vietnam",
    releaseDate: new Date("2024-03-10"),
    specifications: [{ label: "Display", value: "Super AMOLED" }],
    stockStatus: "in-stock",
  },
  {
    name: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    description: "High-value camera phone.",
    price: 399,
    salePrice: 369,
    discountPercentage: 8,
    stock: 140,
    featured: false,
    onSale: true,
    images: ["https://example.com/note13pro.jpg"],
    rating: 4.5,
    reviews: 410,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-01-15"),
    specifications: [{ label: "Camera", value: "200MP" }],
    stockStatus: "in-stock",
  },
  {
    name: "iPhone 15",
    brand: "Apple",
    description: "Reliable flagship iPhone.",
    price: 799,
    salePrice: null,
    discountPercentage: null,
    stock: 90,
    featured: true,
    onSale: false,
    images: ["https://example.com/iphone15.jpg"],
    rating: 4.7,
    reviews: 800,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-09-22"),
    specifications: [{ label: "Chip", value: "A16" }],
    stockStatus: "in-stock",
  },
  {
    name: "Pixel 8a",
    brand: "Google",
    description: "Affordable Pixel with AI.",
    price: 499,
    salePrice: 469,
    discountPercentage: 6,
    stock: 110,
    featured: false,
    onSale: true,
    images: ["https://example.com/pixel8a.jpg"],
    rating: 4.6,
    reviews: 350,
    category: catIds.smartphones,
    countryOfOrigin: "Vietnam",
    releaseDate: new Date("2024-05-01"),
    specifications: [{ label: "AI", value: "Tensor G3" }],
    stockStatus: "in-stock",
  },
  {
    name: "Sony Xperia 5 V",
    brand: "Sony",
    description: "Compact flagship phone.",
    price: 799,
    salePrice: null,
    discountPercentage: null,
    stock: 45,
    featured: false,
    onSale: false,
    images: ["https://example.com/xperia5v.jpg"],
    rating: 4.4,
    reviews: 160,
    category: catIds.smartphones,
    countryOfOrigin: "Japan",
    releaseDate: new Date("2023-09-12"),
    specifications: [{ label: "Camera", value: "Exmor-T" }],
    stockStatus: "in-stock",
  },
  {
    name: "Oppo Reno 11 Pro",
    brand: "Oppo",
    description: "Stylish camera-focused phone.",
    price: 549,
    salePrice: 499,
    discountPercentage: 9,
    stock: 100,
    featured: false,
    onSale: true,
    images: ["https://example.com/reno11.jpg"],
    rating: 4.3,
    reviews: 210,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-02-02"),
    specifications: [{ label: "Portrait", value: "Telephoto" }],
    stockStatus: "in-stock",
  },
  {
    name: "Vivo V30 Pro",
    brand: "Vivo",
    description: "Slim phone with Zeiss optics.",
    price: 599,
    salePrice: null,
    discountPercentage: null,
    stock: 95,
    featured: false,
    onSale: false,
    images: ["https://example.com/v30pro.jpg"],
    rating: 4.4,
    reviews: 180,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2024-03-18"),
    specifications: [{ label: "Lens", value: "ZEISS" }],
    stockStatus: "in-stock",
  },
  {
    name: "Asus Zenfone 11",
    brand: "Asus",
    description: "Compact powerful smartphone.",
    price: 699,
    salePrice: 649,
    discountPercentage: 7,
    stock: 60,
    featured: false,
    onSale: true,
    images: ["https://example.com/zenfone11.jpg"],
    rating: 4.5,
    reviews: 190,
    category: catIds.smartphones,
    countryOfOrigin: "Taiwan",
    releaseDate: new Date("2024-04-20"),
    specifications: [{ label: "Size", value: "Compact" }],
    stockStatus: "in-stock",
  },
  {
    name: "Huawei P60 Pro",
    brand: "Huawei",
    description: "Premium photography phone.",
    price: 899,
    salePrice: null,
    discountPercentage: null,
    stock: 40,
    featured: true,
    onSale: false,
    images: ["https://example.com/p60pro.jpg"],
    rating: 4.6,
    reviews: 220,
    category: catIds.smartphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-05-01"),
    specifications: [{ label: "Camera", value: "XMAGE" }],
    stockStatus: "in-stock",
  },
  {
    name: "Nothing Phone (1)",
    brand: "Nothing",
    description: "Transparent minimalist design.",
    price: 349,
    salePrice: 299,
    discountPercentage: 14,
    stock: 130,
    featured: false,
    onSale: true,
    images: ["https://example.com/nothing1.jpg"],
    rating: 4.2,
    reviews: 300,
    category: catIds.smartphones,
    countryOfOrigin: "UK",
    releaseDate: new Date("2022-07-21"),
    specifications: [{ label: "Design", value: "Transparent" }],
    stockStatus: "in-stock",
  },

  /* ===================== ACCESSORIES (25) ===================== */
  {
    name: "Apple USB-C Cable",
    brand: "Apple",
    description: "Fast charging USB-C cable.",
    price: 29,
    salePrice: null,
    discountPercentage: null,
    stock: 300,
    featured: false,
    onSale: false,
    images: ["https://example.com/apple-cable.jpg"],
    rating: 4.5,
    reviews: 900,
    category: catIds.accessories,
    countryOfOrigin: "China",
    releaseDate: new Date("2022-09-01"),
    specifications: [{ label: "Length", value: "1m" }],
    stockStatus: "in-stock",
  },
  {
    name: "Samsung Buds Case Cover",
    brand: "Samsung",
    description: "Protective silicone case.",
    price: 19,
    salePrice: 15,
    discountPercentage: 21,
    stock: 200,
    featured: false,
    onSale: true,
    images: ["https://example.com/buds-cover.jpg"],
    rating: 4.3,
    reviews: 150,
    category: catIds.accessories,
    countryOfOrigin: "Vietnam",
    releaseDate: new Date("2023-03-01"),
    specifications: [{ label: "Material", value: "Silicone" }],
    stockStatus: "in-stock",
  },
  {
    name: "Anker PowerLine Cable",
    brand: "Anker",
    description: "Durable fast-charge cable.",
    price: 25,
    salePrice: 19,
    discountPercentage: 24,
    stock: 260,
    featured: true,
    onSale: true,
    images: ["https://example.com/powerline.jpg"],
    rating: 4.8,
    reviews: 1200,
    category: catIds.accessories,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-01-12"),
    specifications: [{ label: "Durability", value: "12k bends" }],
    stockStatus: "in-stock",
  },
  {
    name: "Spigen Screen Protector",
    brand: "Spigen",
    description: "Tempered glass protection.",
    price: 15,
    salePrice: null,
    discountPercentage: null,
    stock: 500,
    featured: false,
    onSale: false,
    images: ["https://example.com/spigen-glass.jpg"],
    rating: 4.6,
    reviews: 1400,
    category: catIds.accessories,
    countryOfOrigin: "South Korea",
    releaseDate: new Date("2022-06-10"),
    specifications: [{ label: "Hardness", value: "9H" }],
    stockStatus: "in-stock",
  },
  {
    name: "Logitech C920 Webcam",
    brand: "Logitech",
    description: "Full HD webcam.",
    price: 99,
    salePrice: 79,
    discountPercentage: 20,
    stock: 85,
    featured: true,
    onSale: true,
    images: ["https://example.com/c920.jpg"],
    rating: 4.7,
    reviews: 2100,
    category: catIds.accessories,
    countryOfOrigin: "Switzerland",
    releaseDate: new Date("2021-04-05"),
    specifications: [{ label: "Resolution", value: "1080p" }],
    stockStatus: "in-stock",
  },

  /* ===================== CONSOLES (15) ===================== */
  {
    name: "PlayStation 4 Slim",
    brand: "Sony",
    description: "Affordable PlayStation console.",
    price: 299,
    salePrice: 249,
    discountPercentage: 17,
    stock: 60,
    featured: false,
    onSale: true,
    images: ["https://example.com/ps4slim.jpg"],
    rating: 4.6,
    reviews: 3500,
    category: catIds.consoles,
    countryOfOrigin: "China",
    releaseDate: new Date("2018-09-01"),
    specifications: [{ label: "Storage", value: "1TB" }],
    stockStatus: "in-stock",
  },
  {
    name: "Xbox One S",
    brand: "Microsoft",
    description: "4K media gaming console.",
    price: 279,
    salePrice: null,
    discountPercentage: null,
    stock: 55,
    featured: false,
    onSale: false,
    images: ["https://example.com/xboxones.jpg"],
    rating: 4.4,
    reviews: 2800,
    category: catIds.consoles,
    countryOfOrigin: "China",
    releaseDate: new Date("2017-08-02"),
    specifications: [{ label: "Video", value: "4K HDR" }],
    stockStatus: "in-stock",
  },
  {
    name: "Atari VCS",
    brand: "Atari",
    description: "Modern retro console.",
    price: 399,
    salePrice: 299,
    discountPercentage: 25,
    stock: 20,
    featured: false,
    onSale: true,
    images: ["https://example.com/atarivcs.jpg"],
    rating: 4.0,
    reviews: 220,
    category: catIds.consoles,
    countryOfOrigin: "USA",
    releaseDate: new Date("2021-06-15"),
    specifications: [{ label: "OS", value: "Linux-based" }],
    stockStatus: "in-stock",
  },

  /* ===================== GAMES (20) ===================== */
  {
    name: "Cyberpunk 2077",
    brand: "CD Projekt",
    description: "Open-world sci-fi RPG.",
    price: 59,
    salePrice: 29,
    discountPercentage: 51,
    stock: 300,
    featured: true,
    onSale: true,
    images: ["https://example.com/cyberpunk.jpg"],
    rating: 4.6,
    reviews: 5000,
    category: catIds.games,
    countryOfOrigin: "Poland",
    releaseDate: new Date("2020-12-10"),
    specifications: [{ label: "Genre", value: "RPG" }],
    stockStatus: "in-stock",
  },
  {
    name: "Horizon Forbidden West",
    brand: "Guerrilla Games",
    description: "Open-world action RPG.",
    price: 69,
    salePrice: 49,
    discountPercentage: 29,
    stock: 180,
    featured: true,
    onSale: true,
    images: ["https://example.com/horizonfw.jpg"],
    rating: 4.8,
    reviews: 3100,
    category: catIds.games,
    countryOfOrigin: "Netherlands",
    releaseDate: new Date("2022-02-18"),
    specifications: [{ label: "World", value: "Open-world" }],
    stockStatus: "in-stock",
  },
  {
    name: "Resident Evil 4 Remake",
    brand: "Capcom",
    description: "Survival horror remake.",
    price: 59,
    salePrice: null,
    discountPercentage: null,
    stock: 140,
    featured: true,
    onSale: false,
    images: ["https://example.com/re4.jpg"],
    rating: 4.9,
    reviews: 2600,
    category: catIds.games,
    countryOfOrigin: "Japan",
    releaseDate: new Date("2023-03-24"),
    specifications: [{ label: "Genre", value: "Horror" }],
    stockStatus: "in-stock",
  },

  /* ===================== WATCHES (10) ===================== */
  {
    name: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    description: "Advanced health smartwatch.",
    price: 329,
    salePrice: 299,
    discountPercentage: 9,
    stock: 110,
    featured: true,
    onSale: true,
    images: ["https://example.com/watch6.jpg"],
    rating: 4.6,
    reviews: 540,
    category: catIds.watches,
    countryOfOrigin: "South Korea",
    releaseDate: new Date("2023-08-11"),
    specifications: [{ label: "Health", value: "ECG" }],
    stockStatus: "in-stock",
  },
  {
    name: "Garmin Fenix 7",
    brand: "Garmin",
    description: "Outdoor multisport watch.",
    price: 699,
    salePrice: null,
    discountPercentage: null,
    stock: 65,
    featured: true,
    onSale: false,
    images: ["https://example.com/fenix7.jpg"],
    rating: 4.8,
    reviews: 620,
    category: catIds.watches,
    countryOfOrigin: "USA",
    releaseDate: new Date("2022-01-18"),
    specifications: [{ label: "GPS", value: "Multi-band" }],
    stockStatus: "in-stock",
  },

  /* ===================== HEADPHONES (5) ===================== */
  {
    name: "AirPods Pro 2",
    brand: "Apple",
    description: "Premium ANC earbuds.",
    price: 249,
    salePrice: 229,
    discountPercentage: 8,
    stock: 150,
    featured: true,
    onSale: true,
    images: ["https://example.com/airpodspro2.jpg"],
    rating: 4.8,
    reviews: 4200,
    category: catIds.headphones,
    countryOfOrigin: "China",
    releaseDate: new Date("2023-09-22"),
    specifications: [{ label: "ANC", value: "Adaptive" }],
    stockStatus: "in-stock",
  },
  {
    name: "JBL Tune 760NC",
    brand: "JBL",
    description: "Affordable ANC headphones.",
    price: 129,
    salePrice: 99,
    discountPercentage: 23,
    stock: 170,
    featured: false,
    onSale: true,
    images: ["https://example.com/tune760.jpg"],
    rating: 4.4,
    reviews: 880,
    category: catIds.headphones,
    countryOfOrigin: "USA",
    releaseDate: new Date("2022-05-10"),
    specifications: [{ label: "ANC", value: "Active" }],
    stockStatus: "in-stock",
  },
];

const createdProducts = await Product.insertMany(products);

// 3. Seed Users
const users = [
  {
    name: "Admin User",
    email: "admin@ecommerce.com",
    password: "admin123",
    role: "Admin",
    phone: "123-456-7890",
    address: "123 Admin St, City, Country",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    password: "password123",
    role: "User",
    phone: "987-654-3210",
    address: "456 User Ave, City, Country",
  },
];

const createdUsers = await User.insertMany(users);

// 4. Seed a Sample Order
const sampleOrder = {
  user: createdUsers[1]._id,
  items: [
    {
      product: createdProducts[0]._id, // iPhone 16 Pro
      name: createdProducts[0].name,
      image: createdProducts[0].images[0],
      price: createdProducts[0].salePrice || createdProducts[0].price,
      quantity: 1,
    },
    {
      product: createdProducts[6]._id, // Rugged Phone Case
      name: createdProducts[6].name,
      image: createdProducts[6].images[0],
      price: createdProducts[6].price,
      quantity: 2,
    },
  ],
  shippingAddress: {
    street: "789 Sample Road",
    city: "New York",
    state: "NY",
    country: "USA",
    zipCode: "10001",
  },
  paymentMethod: "Credit Card",
  paymentStatus: "paid",
  status: "Delivered",
  totalAmount:
    (createdProducts[0].salePrice || createdProducts[0].price) +
    createdProducts[6].price * 2,
};

await Order.create(sampleOrder);

console.log("Seed data inserted successfully!");
console.log(`Categories: ${createdCategories.length}`);
console.log(`Products: ${createdProducts.length}`);
console.log(`Users: ${createdUsers.length}`);
console.log(`Sample Order: 1`);

await mongoose.disconnect();
